name: Windows build and test

# Run on main (after PRs land) to ensure that they aren't heinously breaking the
# Windows build.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Build CIRCT and run its tests.
  build-circt:
    name: Build and Test
    uses: ./.github/workflows/unifiedBuildTestAndInstall.yml
    with:
      runner: windows-2022
      cmake_build_type: release
      llvm_enable_assertions: ON
      build_shared_libs: OFF
      llvm_force_enable_stats: ON
      runTests: true
      cmake_c_compiler: cl
      cmake_cxx_compiler: cl
